[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002167C42F770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db00ea3e98bc2c55f53163edc3e9ffcb/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002167C42FA40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db00ea3e98bc2c55f53163edc3e9ffcb/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002167C42FE00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db00ea3e98bc2c55f53163edc3e9ffcb/element