[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002AD8A497B60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/71a928ca6dd2ae0965ad572d1c005eb5/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002AD87D638C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/71a928ca6dd2ae0965ad572d1c005eb5/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002AD8A497EC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/71a928ca6dd2ae0965ad572d1c005eb5/element