[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FC462BFC80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d131abeacbd1fc18411804228821a460/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FC462BFA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d131abeacbd1fc18411804228821a460/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FC462BFF20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d131abeacbd1fc18411804228821a460/element